INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (3, 'Books');


INSERT INTO SUPPLIER (ID, NAME) VALUES (1, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (2, 'Amazon');

INSERT INTO PRODUCT (id, NAME, FK_SUPPLIER, FK_CATEGORY, Quantity_Available) VALUES (1, 'Crise nas Infinitas Terras', 1, 1, 10);

INSERT INTO PRODUCT (id, NAME, FK_SUPPLIER, FK_CATEGORY, Quantity_Available) VALUES (2, 'Interestelar', 2,3,5);

INSERT INTO PRODUCT (id, NAME, FK_SUPPLIER, FK_CATEGORY, Quantity_Available) VALUES (3, 'Harry Potter', 2,3,4);