INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1003, 'Books');


INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'Amazon');

INSERT INTO PRODUCT (id, NAME, FK_SUPPLIER, FK_CATEGORY, Quantity_Available) VALUES (1001, 'Crise nas Infinitas Terras', 1000, 1000, 10);

INSERT INTO PRODUCT (id, NAME, FK_SUPPLIER, FK_CATEGORY, Quantity_Available) VALUES (1002, 'Interestelar', 1002,1002,5);

INSERT INTO PRODUCT (id, NAME, FK_SUPPLIER, FK_CATEGORY, Quantity_Available) VALUES (1003, 'Harry Potter', 1002,1002,4);